# File from https://github.com/kubeedge/kubeedge/tree/master/build/cloud

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  name: cloudcore
  namespace: kubeedge
