apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-cloud
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        placement: cloud
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-cloud
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http-0
      port: 80
      targetPort: 80