apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-edge
  labels:
    app: nginx-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-edge
  template:
    metadata:
      labels:
        app: nginx-edge
    spec:
      nodeSelector:
        placement: edge
        type: rasp4
      containers:
      - name: nginx
        image: new:nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-edge
  ports:
    - name: http-0
      port: 1200
      protocol: TCP
      targetPort: 80
